---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 2048
    cpus: 4
  network:
    - ["forwarded_port", {guest: 8443, host: 8443}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: package
    run_list:
    - recipe[lxd]
  - name: source
    run_list:
    - recipe[lxd]
    attributes:
      lxd:
        install_method: 'source'
        tcp_ip: '0.0.0.0'
        tcp_port: '8443'
